//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Movie_Id { get; set; }
        public string MovieName { get; set; }
        public Nullable<System.DateTime> DateOfRelease { get; set; }
        public string Producer { get; set; }
    }
}
